### ISSUE TITLE
Project ongoing or abandoned

### ISSUE THREAD

**Issue by mallyaakash** [MichaelsPlayground/NfcMifareUltralightExample#1]
Hey Michael, was wondering if this project is ongoing or not. I was trying to find solutions to write data to my nfc ring and couldn't really find any free or usable tools as MIFARE Classic Tool does not work with ultralight. Would be great if you could create a release I can use on my android phone. Appreciate your work and this project!

**Comment by MichaelsPlayground** [comment]
You are right, the project is currently just a "stub" - it was copied from another project but not filled with life. I'm planning to work on this project within the next week, but please keep in mind that this "playground" has a lot of unfinished projects. Just have a close look to this project repository  and you will find updates - I will update the "readme.md" document to show any project milestones.

Just a question - is your NFC ring really an "Mifare Ultralight card" ? The user memory of these cards is just 144 bytes.

Greetings
Michael

**Comment by MichaelsPlayground** [comment]
Dear mallyaakash and other readers,
I decided to stop any work on this repository as it uses the Mifare Ultralight class for accessing the tag. Unfortunately this class is not available on all Android devices. 
I setup two new repositories that are using the NfcA class - this class is available on all Android devices with NFC capabilities.

**MIFARE Ultralight C tag**: https://github.com/AndroidCrypto/MIFARE_Ultralight_C_Explorer

Tutorial for the MIFARE Ultralight C Explorer: https://medium.com/@androidcrypto/explore-a-mifare-ultralight-c-nfc-tag-android-java-e6408b1030cf

**MIFARE Ultralight EV1 tag**: https://github.com/AndroidCrypto/MIFARE_Ultralight_EV1_Explorer

Tutorial for the MIFARE Ultralight EV1 Explorer: https://medium.com/@androidcrypto/explore-a-mifare-ultralight-ev1-nfc-tag-android-java-a23d0b4b0ea5

I'm closing this issue.
Michael
